### PR TITLE
Import / Add /.Update multiple regions

### PR DESCRIPTION
**Pull request by Aximem**
As mentionned in #86 / #139 / #155, we are not able to import / add / update multiple regions at a time.   

For e.g., if I want to initialize my Nominatim Database with multiple regions (monaco and andorra), I have to merge the two region files into a combined one and then use nominatim-docker process.  
Also, with this solution, I loose all possibility of update following @UntitleDude [comment](https://github.com/mediagis/nominatim-docker/issues/139#issuecomment-700005270).  

I developed a solution to manage import / add / update multiple regions following [Nominatim Advanced Installations documentation](https://nominatim.org/release-docs/develop/admin/Advanced-Installations/).  
Now I am able, with nominatim-docker, to : 
- import multiple regions
- add more regions, really helpful in case we have already initialized the database and want to add other regions
- update multiple regions 

I'm not familiar with Dockerfile and shell so there are many improve to make I guess. Also I put every scripts into a separated folder since this is a very different process from the default one but this might not be a good idea. So don't hesitate to tell me how I can improve this pull request and if you think it has its place into nominatim-docker. 

Thanks.

### CODE REVIEW

**Comment by philipkozeny** [comment]
Thanks for the PR. I'll take a look and suggest some changes. FYI: the underlying image / Dockerfiles have changed a lot with PR https://github.com/mediagis/nominatim-docker/pull/183, so we would need to reflect the changes also here. But I'll try to give feedback before you tackle that one.

**Comment by CvekCoding** [comment]
When do you plan to merge this into master branch?

**Comment by leonardehrenfried** [comment]
No current plans since the underlying code has changed dramatically and the version has changed.

**Comment by Aximem** [comment]
@philipkozeny I totally agree. Also it seems that the nominatim repository is currently not maintaining the [multi scripts](https://github.com/osm-search/Nominatim/issues/2365), meaning I have to use an older nominatim version.
Thanks for the feedback.

**Pull request closed without merging**
