### PR TITLE
Fixes #419 Fixes #420

### LINKED ISSUE #419: Error in curl
**Describe the bug**
Please see logs below:

```
---> docker run -it --shm-size=1g   -e PBF_URL=https://download.geofabrik.de/europe/monaco-latest.osm.pbf   -e REPLICATION_URL=https://download.geofabrik.de/europe/monaco-updates/   -e IMPORT_WIKIPEDIA=false   -e NOMINATIM_PASSWORD=very_secure_password   -v nominatim-data:/var/lib/postgresql/14/main   -p 8080:8080   --name nominatim   mediagis/nominatim:4.2
+ tailpid=0
+ replicationpid=0
+ trap stopServices SIGTERM TERM INT
+ /app/config.sh
+ id nominatim
+ useradd -m -p very_secure_password nominatim
+ IMPORT_FINISHED=/var/lib/postgresql/14/main/import-finished
+ '[' '!' -f /var/lib/postgresql/14/main/import-finished ']'
+ /app/init.sh
+ OSMFILE=/nominatim/data.osm.pbf
+ CURL='curl -L -A mediagis/nominatim-docker:4.2.0 --fail-with-body'
+ '[' false = true ']'
+ '[' -f false ']'
+ echo 'Skipping optional Wikipedia importance import'
Skipping optional Wikipedia importance import
+ '[' '' = true ']'
+ '[' -f '' ']'
+ echo 'Skipping optional GB postcode import'
Skipping optional GB postcode import
+ '[' '' = true ']'
+ '[' -f '' ']'
+ echo 'Skipping optional US postcode import'
Skipping optional US postcode import
+ '[' '' = true ']'
+ '[' -f '' ']'
+ echo 'Skipping optional Tiger addresses import'
Skipping optional Tiger addresses import
+ '[' https://download.geofabrik.de/europe/monaco-latest.osm.pbf '!=' '' ']'
+ echo Downloading OSM extract from https://download.geofabrik.de/europe/monaco-latest.osm.pbf
Downloading OSM extract from https://download.geofabrik.de/europe/monaco-latest.osm.pbf
+ curl -L -A mediagis/nominatim-docker:4.2.0 --fail-with-body https://download.geofabrik.de/europe/monaco-latest.osm.pbf -C - --create-dirs -o /nominatim/data.osm.pbf
curl: (6) getaddrinfo() thread failed to start
```

**Expected behavior**
Can run localhost:8080

**Desktop / Server (please complete the following information):**
 - OS & Version: Ubuntu 16.04
 - Docker Version: 20.10.7,
 - Nominatim Version: 4.2

### LINKED ISSUE #420: Cannot cURL nominatim addresses (403 forbidden)
Per my comment in #419 I am getting 403'd with post code and wikimedia downloads enabled. I disabled those and it appears able to download from geofabrik. The other related issues seem to be focused around a blocked user agent and irresponsible folks running this, so I am curious how I continue? Am I forced to download, mount and use those files instead? If so how does that affect automatic updates?

### PR DESCRIPTION
**Pull request by WhereRtheInterwebs**

### CODE REVIEW

**Comment by mtmail** [comment]
You need to set a user agent identifying you (https://github.com/mediagis/nominatim-docker/issues/420#issuecomment-1406177270). Default user agents will be blocked.

**Comment by WhereRtheInterwebs** [comment]
So should the user agent be set in the docker run command as an environment variable when creating the container?  Should the documentation be updated to indicate this is required for these downloads to function?

**Comment by mtmail** [comment]
The maintainer of the server is on holiday. I think the documentation should change but maybe she's fine with the current server traffic (bandwidth, cost) now.

**Comment by leonardehrenfried** [comment]
The user agent should be set as an environment variable at runtime. It's unfortunate that it has to be this way.

Improving the documentation is the way forward in my view.

**Comment by philipkozeny** [comment]
Fixed with https://github.com/mediagis/nominatim-docker/pull/460 since @leonardehrenfried hosts the files now.

**Pull request closed without merging**
