### PR TITLE
Allow to pass env variables to nominatim

### PR DESCRIPTION
**Pull request by xpoinsard**
Allow to pass env variables to nominatim in order to be able to pass proxy information by example

### CODE REVIEW

**Comment by leonardehrenfried** [comment]
LGTM.

**Comment by philipkozeny** [comment]
@xpoinsard thanks! do you have an example on hand how you pass those variables, out of curiosity how you use that feature? Thanks!

**Comment by xpoinsard** [comment]
Just adding proxy env variables to the docker command line :

>   -e https_proxy=http://myproxy:3128/ \\
>   -e http_proxy=http://myproxy:3128/ \\

**Comment by philipkozeny** [comment]
> Just adding proxy env variables to the docker command line :
> 
> > -e https_proxy=http://myproxy:3128/ \
> > -e http_proxy=http://myproxy:3128/ \

Got it, thanks for your contribution!

**Pull request merged**
