### PR TITLE
Refactor Dockerfile

### PR DESCRIPTION
**Pull request by r3pl1x**
#https://github.com/mediagis/nominatim-docker/commit/2058235240825639a784bda507dae77d2f8e1b1e#r56677653

1. There can only be one CMD per Dockerfile. If more than one is defined, only the last will be executed.
2. No need to create the directory "/nominatim" because it will be created by "COPY conf.d/env $PROJECT_DIR/.env"

### CODE REVIEW

**Comment by leonardehrenfried** [comment]
I think there is another one at line 112.

**Comment by leonardehrenfried** [comment]
The unit tests fail. Could you please check this out?

Perhaps rerunning solves it as I can't figure out what the problem is.

**Comment by leonardehrenfried** [comment]
I've remove the extra CMD lines over at #260. Thanks for pointing this out.

Can this be closed?

**Comment by r3pl1x** [comment]
Yeah, it's fine.
My changes can't be the reason for the failing build... I'm already using it in production :P

**Comment by leonardehrenfried** [comment]
These changes are now in the master branch.

BTW, you're right in that it wasn't your change that caused the tests to fail. I had the same problem to run the CI for a few days. Today I re-ran and it worked.

When I tried manually I noticed that the change files were very slow to download from Geofabrik (minutes!) so that was presumably causing problems during the update process.

**Pull request closed without merging**
