### PR TITLE
Fix/gb us postcode import (#1)

### PR DESCRIPTION
**Pull request by iAlex97**
* use gzipped csv instead of sql dumps for uk and us postcodes

* add test case for GB postcode import

### CODE REVIEW

**Comment by iAlex97** [comment]
closes #299

**Comment by iAlex97** [comment]
Although I used the smallest county I could find (pbf is 1.4mb), indexing of postcodes still takes more than 5 minutes.

**Comment by leonardehrenfried** [comment]
This is a really great PR - thanks!

I would like to ask for a small favour: can you make sure that the csv.gz file is deleted here: https://github.com/mediagis/nominatim-docker/blob/master/4.0/init.sh#L103

**Comment by iAlex97** [comment]
Sure thing, I wasn't aware of the cleanup. My bad I didn't scroll the entire script 😅

**Pull request merged**
