### PR TITLE
4.2 upgrade

### PR DESCRIPTION
**Pull request by philipkozeny**
- support nominatim 4.2
- add 4.2 to supported versions (4.0, 4.1, 4.2)
- update 4.1 docs

### CODE REVIEW

**Comment by leonardehrenfried** [comment]
This looks really good. I'm going to wait for the CI to pass before approving.

Thanks!

**Comment by leonardehrenfried** [comment]
We are now supporting 3 versions of nominatim where before we did 2. Is this intentional? 

Not that it's a huge burden but I was wondering.

**Comment by philipkozeny** [comment]
> We are now supporting 3 versions of nominatim where before we did 2. Is this intentional?
> 
> Not that it's a huge burden but I was wondering.

Yeah this time it was intentional since the difference between the versions is marginal and the release cycle of nominatim is way shorter now. Although thinking about it, the base image (Ubuntu 20.x vs 22.x) has changed. So If you also don't have a good argument, I would remove the support from 4.0 :)

**Comment by leonardehrenfried** [comment]
Yes, please remove support for 4.0.

**Comment by leonardehrenfried** [comment]
Ok, and do you still want to build the image?

**Comment by philipkozeny** [comment]
> Ok, and do you still want to build the image?

no, just way too tired and overlooking things :joy: thanks for the catch

**Review by leonardehrenfried — APPROVED** [review]

**Comment by leonardehrenfried** [comment]
You have a [ci skip] in the squashed merge commit so the master ci doesn't run.

**Comment by philipkozeny** [comment]
i know, thanks - i have seen it after the merge. just looking if i can manually trigger it or if i really need to create another commit.

**Pull request merged**
