### PR TITLE
Nominatim v3.2

### PR DESCRIPTION
**Pull request by dlucia**
Docker setup with Nominatim 3.2 and Postgres 10.
This has been tested and it is currently used in a production environment

### CODE REVIEW

**Comment by Zverik** [comment]
Could you please update this to 3.3?

**Comment by winsento** [comment]
@Zverik @dlucia  I'll apply it tonight.

**Comment by dlucia** [comment]
Cool, thanks @winsento. I can do it as well in case you have not time for it :)

**Comment by winsento** [comment]
@dlucia added you to collaborators.

**Comment by winsento** [comment]
@all-contributors please add @dlucia for infrastructure and code.

**Pull request merged**
