### PR TITLE
Setup for building up the image from Nominatim master branch prepared for development

### PR DESCRIPTION
**Pull request by I70l0teN4ik**
I find the docker-compose setup much flexible in terms of local dev env comparing to Vagrant. So I've used this setup to prepare the pull request to Nominatim repo. I guess some one could use it for such purposes as well.
The main difference here:

- image is always build from Dokerfile 
- Dockerfile: clone from repo instead of tar.gz. 
-  docker-compose is prepared for mounting the files need to see changes done in code right away.

### CODE REVIEW

**Comment by leonardehrenfried** [comment]
Hi, thanks for making this pull request.

I've been thinking about this over the last few days and have come to the following conclusion: The code quality is good but I would like to ask you to maintain this on your own fork/repo.

The reasons for this are:

- It deviates from our way of providing a pre-built image that you only need to download
- We focus only on released versions of Nominatim, which this doesn't
- Most importantly: it adds maintenance and QA burden where we would be expected to keep it up to date with the latest changes that we add for the Nominatim release images. This is something that I don't feel like I can take on.

I'm happy linking to your repo to point people to it who want to use Nominatim master.

If @philipkozeny has a different opinion, we can disuss this further.

**Comment by philipkozeny** [comment]
Thanks for the PR, I share @leonardehrenfried's decision. If you need help / pointers with the setup of your fork tell us, we will happily link it in the docs.

**Comment by I70l0teN4ik** [comment]
Ok than. I'll try to keep it up to date. But should I keep as a fork with all the pre-build versions or just make it cleaner and push only the stuff added in `master` folder separately, what would you prefer?
If at some point that would become out of date - it should be at least a good reference of how to achieve same result...

**Comment by leonardehrenfried** [comment]
Personally I would go with a single folder, so just the master stuff. But it's your repo, do whatever is easiest for you.

**Pull request closed without merging**
