### PR TITLE
install logrotate

### PR DESCRIPTION
**Pull request by philipkozeny**
fixes https://github.com/mediagis/nominatim-docker/issues/205

### CODE REVIEW

**Comment by leonardehrenfried** [comment]
Does this also execute `logrotate` at some predefined time?

**Comment by leonardehrenfried** [comment]
I'm asking because I haven't been able to properly run cron in a container as there seemed to be quite a few pitfalls with running background daemons.

**Comment by philipkozeny** [comment]
Cron will be installed + a `cron.daily` conf is created with that install. 

I am testing it right now in my containers, will report back if it runs correctly for a few days. Thanks for the info, haven't had problems with cron before.

**Comment by leonardehrenfried** [comment]
Yeah, not sure if it is relevant but there is also this: https://github.com/mediagis/nominatim-docker/blob/master/3.6/Dockerfile#L9-L11

**Comment by philipkozeny** [comment]
> Yeah, not sure if it is relevant but there is also this: https://github.com/mediagis/nominatim-docker/blob/master/3.6/Dockerfile#L9-L11

great catch!

**Comment by leonardehrenfried** [comment]
Another way to solve this would be to use Apache's piped log feature in combination with its `rotatelogs` program:

- https://httpd.apache.org/docs/current/logs.html#piped
- https://httpd.apache.org/docs/current/programs/rotatelogs.html

Perhaps this is less work to configure.

**Pull request closed without merging**
