### PR TITLE
making CONST_Replication_Url configurabel via --build-arg

### PR DESCRIPTION
**Pull request by mlechner**
This PR makes the CONST_Replication_Url in local.php configurable in Docker build stage by setting --build-arg DYN_REPL_URL=http://example.com/foo-updates. This makes it easier to build a Nominatim Container based on a specific Geofabrik area without having to change Git tracked files.
If DYN_REPL_URL is not set by --build-arg the default Url will be substituted by the same string - which results in no change.

### CODE REVIEW

**Comment by mlechner** [comment]
Anything new about this PR? Plesse merge or ask back.

**Comment by winsento** [comment]
@mlechner sorry I was unavailable for a long time. Let's update PR?

**Comment by mlechner** [comment]
updated PR

**Comment by philipkozeny** [comment]
Thanks for your PR and input and sorry for the super long wait. This change was implemented in a smilier way with the refactor of the 3.6 version (see: https://github.com/mediagis/nominatim-docker/pull/183)!

**Pull request closed without merging**
