### PR TITLE
Reduce dependencies

### PR DESCRIPTION
**Pull request by jmcker**
It's been awhile since #12 has been updated, but if the reduction is still beneficial, I've fixed the conflicts and propagated the changes to all Dockerfiles.

I see about 150 MB reduction in container size when built with the specified options.

### CODE REVIEW

**Comment by philipkozeny** [comment]
Can you also add the change to 3.4? I'll merge it then, thanks!

**Comment by jmcker** [comment]
Added!

**Comment by philipkozeny** [comment]
@jmcker Thanks! I've just tested it with the 3.4 version, when importing data I get the error:

```
2020-01-08 14:32:59 == Setup DB
Postgres version found: 11
2020-01-08 14:32:59.515 UTC [121] ERROR:  could not open extension control file "/usr/share/postgresql/11/extension/postgis.control": No such file or directory
2020-01-08 14:32:59.515 UTC [121] STATEMENT:  CREATE EXTENSION IF NOT EXISTS postgis
ERROR:  could not open extension control file "/usr/share/postgresql/11/extension/postgis.control": No such file or directory
ERROR: pgsql returned with error code (3)
string(34) "pgsql returned with error code (3)"
```

Does it work for you? Seems like there are now some packages for postgis missing.

**Comment by jmcker** [comment]
Hmm I tried to build it, but had to abandon it before the country grid download finished. I figured I had made it past the `apt` stage and things would be alright.

I'll take a look.

**Comment by philipkozeny** [comment]
@jmcker any update on this? Thanks!

**Comment by philipkozeny** [comment]
Integrated into the 3.5 release.

**Pull request closed without merging**
